<?php
/**
 * RenderingJobStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\RenderingService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Rendering Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\RenderingService\Model;
use \Aurigma\RenderingService\ObjectSerializer;

/**
 * RenderingJobStatus Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\RenderingService
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RenderingJobStatus
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'New';

    public const IN_PROGRESS = 'InProgress';

    public const COMPLETED = 'Completed';

    public const FAILED = 'Failed';

    public const RECOVERED = 'Recovered';

    public const DISCARDED = 'Discarded';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::IN_PROGRESS,
            self::COMPLETED,
            self::FAILED,
            self::RECOVERED,
            self::DISCARDED
        ];
    }
}


